#!/usr/bin/env python3.7
import smtplib
import os
from email import encoders
from email.message import Message
from email.mime.audio import MIMEAudio
from email.mime.base import MIMEBase
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
 
def smtp_filter(email_address):
    email_client = email_address.split('@')
    email_client = email_client[1].split('.')
    if email_client[0].lower() == "gmail":
        return ['smtp.gmail.com', 587]
    elif email_client[0].lower() == "outlook":
        return ['smtp-mail.outlook.com', 587]
    elif email_client[0].lower() == "yahoo":
        return ['smtp.mail.yahoo.com', 587]
    elif email_client[0].lower() == "icloud":
        return ['smtp.mail.me.com', 587]
    return 0


def email_send(sender_email_address, sender_email_address_password, target_email_address, email_body):
    smtp = smtp_filter(sender_email_address)
    server = smtplib.SMTP(smtp[0], smtp[1])
    server.starttls()
    try:
        server.login(sender_email_address, sender_email_address_password)
        server.sendmail(sender_email_address, target_email_address, email_body)
    except:
        print("Some error")
    server.quit()

def email_header(sender_email_address, sender_email_address_password, target_email_address, email_subject, email_body, email_attachments = None):
    msg = MIMEMultipart()
    msg['From'] = sender_email_address
    msg['To'] = target_email_address
    msg['Subject'] = email_subject
    
    msg_body = email_body
    msg.attach(MIMEText(msg_body, 'plain'))

    if email_attachments != None:
        filename = "README.md"
        attachment = open(filename, "rb")
        part = MIMEBase('application', 'octet-stream')
        part.set_payload((attachment).read())
        encoders.encode_base64(part)
        part.add_header('Content-Disposition', "attachment; filename= %s" % filename)
        msg.attach(part)

    full_message = msg.as_string()
    email_send(sender_email_address, sender_email_address_password, target_email_address, full_message)

email_header("sender_email_address", "sender_email_address_password", "target_email_address", "email_subject", "email_body", "attachment_file")
